services:
  db:
    build: ./docker/postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 127.0.0.1:5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --username postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
