[project]
name = "passkeys-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.14",
    "psycopg-pool>=3.2.6",
    "psycopg[binary]>=3.2.9",
]
